### ISSUE TITLE
str object not callable

### ISSUE THREAD

**Issue by scaery** [0x48piraj/jiraffe#5]
Encounter the following error:

```sh
jiraffe -h
Traceback (most recent call last):
  File "/usr/local/bin/jiraffe", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/jiraffe/__main__.py", line 48, in main
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter, description=style.GREEN(banner) + style.RESET(''), usage=style.GREEN("jiraffe ") + style.YELLOW("[-h] [-t {}]").format(style.UNDERLINE("https://example-jira-instance.com") + style.RESET('') + style.YELLOW('')) + style.RESET(''))
TypeError: 'str' object is not callable
```
Quickfix on Line 8:
```        if sys.platform.lower() == "win32" or "linux":```

Somehow something with the color setup is going worse...

**Comment by ErwinGeirnaert** [comment]
I had the same problem on my Kali, but I had to use "linux2" instead of "linux"

**Comment by 0x48piraj** [comment]
Implemented a hot-fix, should do the job.

**Comment by AlbertoCorleone** [comment]
Please, add "darwin" to the list to fix the issue for OS X users.

**Comment by GeetAksh1** [comment]
I'm also getting the same error "str object is not callable " while running "Jiraffe" on Mac. Please suggest how to resolve the issue. Thanks!
